# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: macOS-10.13

steps:
- bash: |
    set -e
    sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
    brew tap osrf/simulation
    TAP_LOCATION="$(brew --repo osrf/simulation)"
    sudo rm -rf "$TAP_LOCATION"
    sudo ln -s "$PWD" "$TAP_LOCATION"
    brew test-bot --fast
  displayName: 'Run brew test-bot'